### ISSUE TITLE
Production deployment  checklist

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#102]
create checklist to get all of the pieces deployed (e.g. stacks, sul-embed with media enabled, wowza plugin)

Prep:
- prod blockers
  - IE issues
  - thumbnail issues
  - wowza prod is ready
- hannah writes announcement
- testing new code with media turned off with production data

Basics:
- purl?
- sul-stacks-prod (incl VM config changes)
  - update shared-configs
  - deploy
- sul-embed (incl. VM config changes)
  - update shared-configs
  - deploy
- wowza prod ?
-  hannah sends announcement

**Comment by ndushay** [comment]
For Wowza Prod to be production ready:
- [ ] upgrade Wowza server on wowza-prod (sul-dlss/media#98)
- [ ] nagios checks (SAR-3212)
- [ ] log retention (sul-dlss/dlss-wowza#33, sul-dlss/media#97, then SAR ticket TBD)
- [ ] exception reporting with honeybadger (sul-dlss/media#109)
- [ ] need `stacks` wowza application set up

**Comment by ndushay** [comment]
note:  explicitly NOT tying deployment to data remediation.
