### ISSUE TITLE
UAT preparation checklist

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#130]
- [ ] determine which purl box will be test environment  (purl-test?  with stacks-test?  and embed-stage?)
- [ ] do we have sufficient objects in stacks-test / purl-test pieces for UAT?
- [ ] Hannah (?) sends  email coordinates with testers:   what to test, which objects in test system are avail, how to give feedback, deadline ...
- [ ] fix thumbnails showing access restriction messages incorrectly displaying (merge sul-dlss/sul-embed/pull/710)

**Comment by ndushay** [comment]
Since we're actually in UAT now, I'm closing this ticket entitled "UAT preparation checklist"
