### ISSUE TITLE
Devops checklist (was: Create and finalize SLA for Media Service)

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#94]
- [x] media overview
- [x] sul-streaming info
- [x] wowza server info
- [x] dlss-wowza plugin
- [x] digital_stacks_rails
- [x] sul-embed
- [x] purl

**Comment by ndushay** [comment]
See sul-dlss/DevOpsDocs/pull/33  re:  **streaming-legacy** cutover status (we did cut over, just a few things remain):
- [x] nagios checks for streaming-legacy (SAR-3210)
- [ ] remove nagios checks for sul-streaming-old (SAR-3210)
- [x] log retention for streaming-legacy (SAR-3211)  
  - [x] add afs path to checklist

**Comment by ndushay** [comment]
See sul-dlss/DevOpsDocs#34  re:  Wowza:
- [x] nagios checks (SAR-3212)
- [ ] log retention (sul-dlss/dlss-wowza#33, sul-dlss/media#97, then SAR ticket TBD)
- [ ] exception reporting with honeybadger (sul-dlss/media#109)
- [ ] upgrade Wowza server on wowza-prod (sul-dlss/media#98)
- [ ] @hannahfrost needs to tweak devopsdocs media page for RiverWalkJazz and libstream

**Comment by ndushay** [comment]
I'm going to close this ticket;  any remaining work will be ticketed separately.
